version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Для GitHub Pages можно указать "/web-yazichOK/"
        BASE_HREF: "/"
    image: web-yazichok:latest
    ports:
      - "8080:80"
    restart: unless-stopped

